version: '4.17.0'
services:
  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB_NAME: fastapi

  postgres:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
